import React from 'react'

export const Rating0 = () => {
  return (
  <div className='absolute border right-0 bottom-0 w-[390px] h-[180px]'>
    <div className='relative flex '>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>0</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>0</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>0</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>0</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>0</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>0</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>0</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>0</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>0</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>0</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>0</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>0</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>0</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>0</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>0</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>0</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>0</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>0</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>0</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>11</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>12</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>13</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>14</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>15</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>16</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>17</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>18</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>19</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>20</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>21</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>22</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>1</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>23</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>24</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
      </div>
      <div className='flex-col text-[10px] justify-center items-center'>
        <div className='flex justify-center border w-[15px] h-[15px]'>25</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
        <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
      </div>
    </div>

  </div>
  )
}

export const Rating1 = () => {
  return (
    <div className='absolute border right-0 bottom-0 w-[390px] h-[180px]'>
      <div className='relative flex '>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>26</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
        </div>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>27</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
        </div>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>28</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
        </div>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>29</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
        </div>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>30</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
        </div>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>31</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>2</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
        </div>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>32</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
        </div>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>33</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
        </div>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>34</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>11</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>11</div>
        </div>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>35</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>11</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>12</div>
        </div>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>36</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>11</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>11</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>12</div>
        </div>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>37</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>11</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>12</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>12</div>
        </div>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>38</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>3</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>11</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>12</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>13</div>
        </div>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>39</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>11</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>11</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>12</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>13</div>
        </div>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>40</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>5</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>11</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>11</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>12</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>13</div>
        </div>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>41</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>11</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>12</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>12</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>13</div>
        </div>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>42</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>11</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>12</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>13</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>13</div>
        </div>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>43</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>11</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>12</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>13</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>14</div>
        </div>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>44</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>11</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>12</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>13</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>14</div>
        </div>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>45</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>11</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>12</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>13</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>14</div>
        </div>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>46</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>12</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>13</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>13</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>14</div>
        </div>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>47</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>11</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>12</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>13</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>13</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>15</div>
        </div>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>48</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>9</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>12</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>12</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>13</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>13</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>15</div>
        </div>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>49</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>7</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>12</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>12</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>13</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>14</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>15</div>
        </div>
        <div className='flex-col text-[10px] justify-center items-center'>
          <div className='flex justify-center border w-[15px] h-[15px]'>50</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>*</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>4</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>6</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>8</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>10</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>12</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>12</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>13</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>15</div>
          <div className='flex justify-center border w-[15px] h-[15px]'>15</div>
        </div>
      </div>
    </div>
  )
}