export type itemType = {
  bag:{
    id:number,name:string,price:number,min:number,max:number
  }[],
  camp:{
    id:number,name:string,price:number,min:number,max:number
  }[],
  lighting:{
    id:number,name:string,price:number,min:number,max:number
  }[],
  tool:{
    id:number,name:string,price:number,min:number,max:number
  }[],
  others:{
    id:number,name:string,price:number,min:number,max:number
  }[],
  food:{
    id:number,name:string,price:number,min:number,max:number
  }[],
  horse:{
    id:number,name:string,price:number,min:number,max:number
  }[],
  inn:{
    id:number,name:string,price:number,min:number,max:number
  }[],
  livingExp:{
    id:number,name:string,price:number,min:number,max:number
  }[]
}
export type itemActionType = {
  success:string,
  error:string
}