export type weaponType = {
  sword:{
    id:number,name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  twoHandsSword:{
    id:number,name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  axe:{
    id:number,name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  spear:{
    id:number,name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  mace:{
    id:number,name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  club:{
    id:number,name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  staff:{
    id:number,name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  flail:{
    id:number,name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  warHammer:{
    id:number,name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  bow:{
    id:number,name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  crossBow:{
    id:number,name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  sling:{
    id:number,name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  rock:{
    id:number,name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  throwing:{
    id:number,name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  crannequin:{
    id:number,name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  others:{
    id:number,name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  arrow:{
    id:number,name:string,stock:number,price:number,
  }[],
}
export type weaponActionType = {
  success:string,
  error:string
}