export type weaponType = {
  sword:{
    name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  twoHandsSword:{
    name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  axe:{
    name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  spear:{
    name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  mace:{
    name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  club:{
    name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  staff:{
    name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  flail:{
    name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  warHammer:{
    name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  bow:{
    name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  crossBow:{
    name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  sling:{
    name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  rock:{
    name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  throwing:{
    name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  crannequin:{
    name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  others:{
    name:string,hand1:number,hand2:number,min:number,max:number,multiplication:number,addition:number
  }[],
  arrow:{
    name:string,stock:number,price:number,
  }[],
}