export const shamanMagicList = {
  fire:[
    {ID:'f1',Lv:"Lv1",name:'ファイア・ボルト',sp:5,range:10,effect:'個人',time:'一瞬',category:'ダメージ(炎系)',magnification:'達成値,距離,目標数,ダメージの確実性',resist:'効果減少',content:'目標に打撃力10の炎のダメージを与える'},
    {ID:'f2',Lv:"Lv3",name:'コントロール・スピリット',sp:15,range:10,effect:'下位精霊一つ',time:'永続',category:'目標値 対抗/優越(フルコントロール・スピリット) 被対抗/優越(フルコントロール・スピリット)',magnification:'達成値,距離',resist:'なし',content:'一種類の精霊を召喚し、支配する。'},
    {ID:'f3',Lv:"Lv6",name:'スピリットウォール',sp:30,range:30,effect:'10*3*0.5',time:'一時間',category:'目標値 ダメージ(炎系) 対抗/消滅(Sウォール・ウンディーネ/フラウ) 被対抗/消滅(Sウォール・ウンディーネ/フラウ) 被対抗/優越(H・プロテクションサークル)',magnification:'達成値,持続時間,距離,目標体積',resist:'効果消滅',content:'精霊用いて壁を作る。サラマンダー('},
    {ID:'f4',Lv:"Lv6",name:'スピリットウォール',sp:30,range:30,effect:'10*3*0.5',time:'一時間',category:'目標値 対抗/消滅(Sウォール・サラマンダー) 被対抗/消滅(Sウォール・サラマンダー) 被対抗/優越(クリエイト・ゴーストシップ)',magnification:'達成値,持続時間,距離,目標体積',resist:'効果消滅',content:'精霊用いて壁を作る。'},
    {ID:'f5',Lv:"Lv7",name:'フルコントロール・スピリット',sp:35,range:10,effect:'下位精霊一つ',time:'永続',category:'目標値 対抗/優越(コントロール・スピリット) 被対抗/優越(コントロール・スピリット)',magnification:'達成値,距離',resist:'なし',content:'一種類の精霊を召喚し、完全に支配する。(サラマンダー)'},
  ],
  water:[
    {ID:'wa1',Lv:"Lv1",name:'ピュリフィケーション',sp:3,range:10,effect:'10リットルの水',time:'一瞬',category:'なし',magnification:'達成値,距離,目標体積',resist:'なし',content:'水の中の不純物を取り除く'},
    {ID:'wa2',Lv:"Lv2",name:'ウォーター・スクリーン',sp:6,range:10,effect:'個人',time:'18ラウンド',category:'なし',magnification:'持続時間,距離,目標数',resist:'なし',content:'炎によるダメージを1点軽減する。'},
    {ID:'wa3',Lv:"Lv3",name:'ウォーター・ブリージング',sp:9,range:10,effect:'個人',time:'1時間',category:'目標値',magnification:'達成値,持続時間,距離,目標数',resist:'なし',content:'水の中で呼吸を可能にする。'},
    {ID:'wa4',Lv:"Lv3",name:'コントロール・スピリット',sp:15,range:10,effect:'下位精霊一つ',time:'永続',category:'目標値 対抗/優越(フルコントロール・スピリット) 被対抗/優越(フルコントロール・スピリット)',magnification:'達成値,距離',resist:'なし',content:'一種類の精霊を召喚し、支配する。'},
    {ID:'wa5',Lv:"Lv4",name:'ウォーター・ウォーキング',sp:12,range:10,effect:'個人',time:'一時間',category:'対抗/消滅(シンク) 被対抗/消滅(シンク)',magnification:'達成値,持続時間,距離,目標数',resist:'効果消滅',content:'水の上を歩けるようになる。'},
    {ID:'wa6',Lv:"Lv4",name:'シンク',sp:16,range:10,effect:'個人か小舟',time:'一時間',category:'対抗/消滅(ウォーター・ウォーキング) 被対抗/消滅(ウォーター・ウォーキング) 被対抗/優越(クリエイト・ゴーストシップ)',magnification:'達成値,持続時間,距離,目標数',resist:'効果消滅',content:'水の浮力をなくし、沈ませる'},
    {ID:'wa7',Lv:"Lv6",name:'スピリットウォール',sp:30,range:30,effect:'10*3*0.5',time:'一時間',category:'目標値 対抗/消滅(Sウォール・サラマンダー) 被対抗/消滅(Sウォール・サラマンダー)',magnification:'達成値,持続時間,距離,目標体積',resist:'効果消滅',content:'精霊用いて壁を作る。(ウンディーネ)'},
    {ID:'wa8',Lv:"Lv6",name:'ディクリース・ウォータープレッシャー',sp:24,range:10,effect:'個人',time:'一時間',category:'目標値',magnification:'達成値,持続時間,距離,目標数',resist:'なし',content:'潜水時の水圧を緩和する。'},
    {ID:'wa9',Lv:"Lv7",name:'フルコントロール・スピリット',sp:35,range:10,effect:'下位精霊一つ',time:'永続',category:'目標値 対抗/優越(コントロール・スピリット) 被対抗/優越(コントロール・スピリット)',magnification:'達成値,距離',resist:'なし',content:'一種類の精霊を召喚し、完全に支配する。(ウンディーネ)'},
  ],
  wind:[
    {ID:'w1',Lv:"Lv1",name:'ウィンドボイス',sp:3,range:500,effect:'半径5メートルの空間',time:'一時間',category:'探知',magnification:'持続時間,距離,範囲面積',resist:'なし',content:'目標お場所に発生してる音を聞く。'},
    {ID:'w2',Lv:"Lv3",name:'コントロール・スピリット',sp:15,range:10,effect:'下位精霊一つ',time:'永続',category:'目標値 対抗/優越(フルコントロール・スピリット) 被対抗/優越(フルコントロール・スピリット)',magnification:'達成値,距離',resist:'なし',content:'一種類の精霊を召喚し、支配する。'},
    {ID:'w3',Lv:"Lv3",name:'サイレンス',sp:15,range:30,effect:'半径5メートルの空間',time:'18ラウンド',category:'対抗/優越(リプレイ・サウンド,コントロール・サウンド)',magnification:'達成値,持続時間,距離,範囲面積',resist:'効果消滅',content:'効果範囲内のあらゆる音を消す。'},
    {ID:'w4',Lv:"Lv3",name:'ミュート',sp:9,range:10,effect:'個人',time:'18ラウンド',category:'なし',magnification:'達成値,持続時間,距離,目標数',resist:'効果消滅',content:'目標の発する音を消す。'},
    {ID:'w5',Lv:"Lv5",name:'シュートアロー',sp:20,range:30,effect:'個人',time:'一瞬',category:'対抗/消滅(ミサイル・プロテクション)',magnification:'恐怖,目標数',resist:'なし',content:'目標に自動的に打撃力20の矢のダメージを与える'},
    {ID:'w6',Lv:"Lv5",name:'ミサイル・プロテクション',sp:20,range:20,effect:'半径5メートルの空間',time:'18ラウンド',category:'被対抗/消滅(シュート・アロー)',magnification:'持続時間,距離,範囲面積',resist:'なし',content:'飛び道具の攻撃から身を守る。'},
    {ID:'w7',Lv:"Lv6",name:'コントロール・サウンド',sp:24,range:0,effect:'半径30メートルの空間',time:'集中の限り',category:'集中 対抗/優越(サイレンス)',magnification:'達成値,範囲面積',resist:'効果消滅',content:'効果範囲内の音の響きを操作する。'},
    {ID:'w8',Lv:"Lv6",name:'スピリットウォール',sp:30,range:30,effect:'10*3*0.5',time:'一時間',category:'目標値',magnification:'達成値,持続時間,距離,目標体積',resist:'効果消滅',content:'精霊用いて壁を作る。(シルフ)'},
    {ID:'w9',Lv:"Lv6",name:'ブリザーブ・サウンド',sp:30,range:10,effect:'半径5メートルの空間',time:'音を伝えるまで',category:'なし',magnification:'距離,範囲面積',resist:'なし',content:'特定の場所に音を記録し、伝える。'},
    {ID:'w10',Lv:"Lv7",name:'フルコントロール・スピリット',sp:35,range:10,effect:'下位精霊一つ',time:'永続',category:'目標値 対抗/優越(コントロール・スピリット) 被対抗/優越(コントロール・スピリット)',magnification:'達成値,距離',resist:'なし',content:'一種類の精霊を召喚し、完全に支配する。(シルフ)'},
  ],
  earth:[
    {ID:'e1',Lv:"Lv1",name:'スネア',sp:3,range:10,effect:'個人',time:'一瞬',category:'なし',magnification:'達成値,距離,目標数',resist:'効果消滅',content:'目標を転倒させる。'},
    {ID:'e2',Lv:"Lv2",name:'ホールド',sp:10,range:10,effect:'個人',time:'18ラウンド',category:'なし',magnification:'達成値,距離,持続時間,目標数',resist:'効果消滅',content:'相手の動きを止める。'},
    {ID:'e3',Lv:"Lv3",name:'コントロール・スピリット',sp:15,range:10,effect:'下位精霊一つ',time:'永続',category:'目標値 対抗/優越(フルコントロール・スピリット) 被対抗/優越(フルコントロール・スピリット)',magnification:'達成値,距離',resist:'なし',content:'一種類の精霊を召喚し、支配する。'},
    {ID:'e4',Lv:"Lv3",name:'ストーン・ブラスト',sp:12,range:30,effect:'個人',time:'一瞬',category:'ダメージ(つぶて系)',magnification:'達成値,距離,目標数,ダメージの確実性',resist:'効果減少',content:'打撃力20の石のつぶてのダメージを与える'},
    {ID:'e5',Lv:"Lv4",name:'トンネル',sp:16,range:10,effect:'半径1M、長さ10M',time:'18ラウンド',category:'対抗/優越(Sウォール・ノーム)',magnification:'達成値,持続時間,目標体積',resist:'特殊',content:'地面や石壁などに穴を開ける。'},
    {ID:'e6',Lv:"Lv6",name:'スピリットウォール',sp:30,range:30,effect:'10*3*0.5',time:'一時間',category:'目標値 被対抗/優越(トンネル)',magnification:'達成値,持続時間,距離,目標体積',resist:'なし',content:'精霊用いて壁を作る。(ノーム)'},
    {ID:'e7',Lv:"Lv7",name:'フルコントロール・スピリット',sp:35,range:10,effect:'下位精霊一つ',time:'永続',category:'目標値 対抗/優越(コントロール・スピリット) 被対抗/優越(コントロール・スピリット)',magnification:'達成値,距離',resist:'なし',content:'一種類の精霊を召喚し、完全に支配する。(ノーム)'},
  ],
  l_d_p:[
    {ID:'l1',Lv:"Lv2",name:'ウィル・オー・ウィスプ',sp:6,range:20,effect:'半径5メートルの空間',time:'一時間',category:'ダメージ(純エネルギー系) 対抗/消滅(シェイド,Sウォール・シェイド) 被対抗/消滅(シェイド,Sウォール・シェイド) 被対抗/優越(ダークネス)',magnification:'達成値,持続時間,距離,目標数,ダメージの確実性',resist:'効果減少',content:'効果範囲内を照らす,打撃力10のダメージを与える'},
    {ID:'l2',Lv:"Lv6",name:'スピリットウォール',sp:30,range:30,effect:'10*3*0.5',time:'一時間',category:'目標値 ダメージ(純エネルギー系) 対抗/消滅(シェイド,Sウォール・シェイド) 被対抗/消滅(シェイド,Sウォール・シェイド) 被対抗/優越(ダークネス)',magnification:'達成値,持続時間,距離,目標体積',resist:'効果減少',content:'精霊用いて壁を作る。(ウィスプ)'},
    {ID:'d1',Lv:"Lv2",name:'ウィル・オー・ウィスプ',sp:6,range:20,effect:'半径5メートルの空間',time:'一時間',category:'ダメージ(精神系) 対抗/消滅(ウィスプ,Sウォール・ウィスプ) 被対抗/消滅(ウィスプ,Sウォール・ウィスプ) 被対抗/優越(ライト,ホーリー・ライト)',magnification:'達成値,持続時間,距離,目標数,ダメージの確実性',resist:'効果減少',content:'効果範囲内の自然な光を打消して暗闇に閉ざす。'},
    {ID:'d2',Lv:"Lv4",name:'フィア',sp:12,range:10,effect:'個人',time:'18ラウンド',category:'精神',magnification:'達成値,持続時間,距離,目標数,効果',resist:'効果消滅',content:'相手を恐怖におとしいれる。'},
    {ID:'d3',Lv:"Lv6",name:'スピリットウォール',sp:30,range:30,effect:'10*3*0.5',time:'一時間',category:'目標値 ダメージ(精神系) 対抗/消滅(ウィスプ,Sウォール・ウィスプ) 被対抗/消滅(ウィスプ,Sウォール・ウィスプ)) 被対抗/優越(ライト,ホーリー・ライト)',magnification:'達成値,持続時間,距離,目標体積,ダメージの確実性',resist:'効果減少',content:'精霊用いて壁を作る。(シェイド)'},
    {ID:'p1',Lv:"Lv3",name:'バインディング',sp:12,range:10,effect:'個人',time:'18ラウンド',category:'なし',magnification:'達成値,持続時間,距離,目標数',resist:'効果消滅',content:'目標の動きを封じる。'},
    {ID:'p2',Lv:"Lv5",name:'チャーム',sp:25,range:20,effect:'個人',time:'一週間',category:'精神,目標値',magnification:'達成値,持続時間,距離,目標数',resist:'効果消滅',content:'目標を魅了する。'},
    {ID:'p3',Lv:"Lv6",name:'スピリットウォール',sp:30,range:30,effect:'10*3*0.5',time:'一時間',category:'目標値',magnification:'達成値,持続時間,距離,目標体積',resist:'なし',content:'精霊用いて壁を作る。(ドライアード)'},
  ],
  mind:[
    {ID:'m1',Lv:"Lv1",name:'デストラクション',sp:3,range:10,effect:'個人',time:'1ラウンド',category:'精神',magnification:'達成値,持続時間,距離,目標数',resist:'効果消滅',content:'相手の精神集中を攪乱する。'},
    {ID:'m2',Lv:"Lv2",name:'コンフュージョン',sp:6,range:10,effect:'個人',time:'18ラウンド',category:'精神',magnification:'達成値,持続時間,距離,目標数',resist:'効果消滅',content:'目標を混乱させる。'},
    {ID:'m3',Lv:"Lv2",name:'ファナティシズム',sp:6,range:10,effect:'個人',time:'18ラウンド',category:'精神',magnification:'達成値,持続時間,距離,目標数',resist:'効果消滅',content:'目標の精神を高揚させる。攻撃力＋２回避力ー２'},
    {ID:'m4',Lv:"Lv2",name:'フォーゲット',sp:8,range:10,effect:'個人',time:'18ラウンド',category:'精神',magnification:'達成値,持続時間,距離,目標数',resist:'効果消滅',content:'目標の記憶を失わせる。'},
    {ID:'m5',Lv:"Lv3",name:'インビジブリティ',sp:12,range:0,effect:'術者',time:'集中の限り',category:'集中,幻覚',magnification:'なし',resist:'なし',content:'術の姿を消す。'},
    {ID:'m6',Lv:"Lv3",name:'コントロール・スピリット',sp:15,range:10,effect:'下位精霊一つ',time:'永続',category:'目標値 対抗/優越(フルコントロール・スピリット) 被対抗/優越(フルコントロール・スピリット)',magnification:'達成値,距離',resist:'なし',content:'一種類の精霊を召喚し、支配する。(レプラコーン、スプライト)'},
    {ID:'m7',Lv:"Lv4",name:'スリープ',sp:20,range:0,effect:'個人',time:'永続',category:'精神,目標値',magnification:'達成値,距離',resist:'効果消滅',content:'相手を永遠の眠りにつかせる。'},
    {ID:'m8',Lv:"Lv5",name:'バルキリー・ジャベリン',sp:25,range:20,effect:'個人',time:'一瞬',category:'ダメージ(純エネルギー系)',magnification:'達成値,距離,目標数,ダメージの確実性',resist:'効果減少',content:'打撃力30のエネルギーの投げやりのダメージを与える'},
    {ID:'m9',Lv:"Lv7",name:'バルキリー・ブレッシング',sp:28,range:10,effect:'個人',time:'18ラウンド',category:'目標値',magnification:'達成値,持続時間,距離,目標数',resist:'なし',content:'目標の防具に50点のエネルギー防護施す。'},
  ],
  other:[
    {ID:'o1',Lv:"Lv1",name:'ブラウニー',sp:3,range:0,effect:'建物の中',time:'術者が寝てる間',category:'なし',magnification:'なし',resist:'なし',content:'家の中の雑用をやらせる。'},
    {ID:'o2',Lv:"Lv3",name:'コントロール・スピリット',sp:15,range:10,effect:'下位精霊一つ',time:'永続',category:'目標値 対抗/優越(フルコントロール・スピリット) 被対抗/優越(フルコントロール・スピリット)',magnification:'達成値,距離',resist:'なし',content:'一種類の精霊を召喚し、支配する。(ブラウニー)'},
    {ID:'o3',Lv:"Lv3",name:'ヒーリング',sp:15,range:0,effect:'個人',time:'一瞬',category:'なし',magnification:'なし',resist:'効果消滅',content:'目標の傷を完全に治す'},
    {ID:'o4',Lv:"Lv4",name:'レストア・ヘルス',sp:20,range:0,effect:'個人',time:'一瞬',category:'なし',magnification:'達成値',resist:'なし',content:'目標が受けた傷や病気を治す。'},
    {ID:'o5',Lv:"Lv6",name:'スピリットウォール',sp:30,range:30,effect:'10*3*0.5',time:'一時間',category:'目標値 対抗/消滅(Sウォール・サラマンダー) 被対抗/消滅(Sウォール・サラマンダー) 被対抗/優越(C・プロテクションサークル)',magnification:'達成値,持続時間,距離,目標体積,ダメージの確実性',resist:'効果消滅',content:'精霊用いて壁を作る。(フラウ)'},
    {ID:'o6',Lv:"Lv7",name:'フルコントロール・スピリット',sp:35,range:10,effect:'下位精霊一つ',time:'永続',category:'目標値 対抗/優越(コントロール・スピリット) 被対抗/優越(コントロール・スピリット)',magnification:'達成値,距離',resist:'なし',content:'一種類の精霊を召喚し、完全に支配する。(ブラウニー)'},
  ],
  top:[
    {ID:'t1',Lv:"Lv7",name:'ウィンドストーム',sp:35,range:30,effect:'半径10メートルの空間',time:'18ラウンド',category:'目標値,ダメージ(かまいたち系)',magnification:'達成値,持続時間,距離,目標数,ダメージの確実性',resist:'効果減少',content:'竜巻を起こし、目標を転倒させ、打撃力10のダメージを与える'},
    {ID:'t2',Lv:"Lv7",name:'クラック',sp:35,range:30,effect:'個人',time:'一瞬',category:'ダメージ(地震系)',magnification:'達成値,距離,目標数,目標体積,ダメージの確実性',resist:'効果消滅',content:'目標を地割れに挟み、打撃力30のダメージを与える'},
    {ID:'t3',Lv:"Lv7",name:'プラントシェル',sp:28,range:0,effect:'半径5M、高さ3M',time:'一日',category:'目標値',magnification:'達成値,持続時間,範囲面積',resist:'なし',content:'草木でできた避難所を作り出す。'},
    {ID:'t4',Lv:"Lv8",name:'アイス・コフィン',sp:32,range:30,effect:'1*1*2',time:'一瞬',category:'なし',magnification:'達成値,距離,目標体積',resist:'効果消滅',content:'氷の柱に相手を閉じ込める。'},
    {ID:'t5',Lv:"Lv8",name:'アイス・ストーム',sp:40,range:30,effect:'半径10メートルの空間',time:'一瞬',category:'ダメージ(冷却系)',magnification:'達成値,距離,範囲面積,ダメージの確実性',resist:'効果減少',content:'氷の嵐を巻き起こし、打撃力30のダメージを与える'},
    {ID:'t6',Lv:"Lv8",name:'カレント',sp:32,range:10,effect:'20メートル幅',time:'一時間',category:'目標値 被対抗/優越(メイルシュトローム)',magnification:'達成値,持続時間,距離',resist:'なし',content:'水の流れる方向を操る。'},
    {ID:'t7',Lv:"Lv8",name:'サフォケイト',sp:40,range:10,effect:'個人',time:'18ラウンドか死亡',category:'目標値',magnification:'達成値,持続時間',resist:'効果消滅',content:'目標を窒息させる。'},
    {ID:'t8',Lv:"Lv8",name:'ナイトメア',sp:40,range:0,effect:'個人',time:'儀式の限り',category:'目標値,呪い',magnification:'達成値',resist:'効果減少',content:'目標に毎夜悪夢をみせて衰弱させる。'},
    {ID:'t9',Lv:"Lv8",name:'ファイアスト－ム',sp:40,range:30,effect:'半径10メートルの空間',time:'一瞬',category:'ダメージ(炎系)',magnification:'達成値,距離,範囲面積,ダメージの確実性',resist:'効果減少',content:'炎の嵐を巻き起こし、打撃力30のダメージを与える'},
    {ID:'t10',Lv:"Lv8",name:'メイズ・ウッズ',sp:40,range:0,effect:'半径500メートルの空間',time:'一日',category:'幻覚,目標値',magnification:'達成値,持続時間,範囲面積',resist:'効果消滅',content:'迷いの森を作り出し、出れなくする。'},
    {ID:'t11',Lv:"Lv9",name:'アースクエイク',sp:45,range:30,effect:'半径10メートルの地面',time:'18ラウンド',category:'目標値,ダメージ(地震系)',magnification:'達成値,持続時間,距離,範囲面積,ダメージの確実性',resist:'効果減少',content:'地震を起こし、目標を転倒させ、打撃力20のダメージを与える'},
    {ID:'t12',Lv:"Lv9",name:'フリーズ',sp:36,range:30,effect:'個人',time:'一瞬',category:'なし',magnification:'達成値,距離,目標数',resist:'効果消滅',content:'目標を瞬間冷凍し、即死させる。'},
    {ID:'t13',Lv:"Lv9",name:'メイルシュトローム',sp:45,range:500,effect:'半径50メートルの水面',time:'18ラウンド',category:'目標値 対抗/優越(カレント)',magnification:'達成値,持続時間,距離,範囲面積',resist:'なし',content:'大渦巻きを作り出し、浮いている人や物を沈める。'},
  ],
  top2:[
    {ID:'t14',Lv:"Lv10",name:'ニュートラライズ・エレメンタル',sp:50,range:0,effect:'半径100メートルの地面',time:'18ラウンド',category:'目標値,対抗/優越(関連する魔法)',magnification:'達成値,持続時間,範囲面積',resist:'なし',content:'精霊力を中和する。'},
  ],
};